spring:
  data:
    mongodb:
      database: chat_app
      uri: mongodb+srv://nmq126:9cl2JhJ6KXhhrH99@cluster0.umjmd.mongodb.net/
server:
  port: 8088
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
